[package]
edition = "2021"
name = "sublist"
version = "0.0.0"

[features]
grapheme = []

[dependencies]
grapheme = "0.0.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
